modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Followers%20Teleport%20Too"
logoFile="icon.png"

[[mods]]
modId="followersteleporttoo"
version="2.4"
displayName="Followers Teleport Too"
displayURL="https://serilum.com/mod/followers-teleport-too"
authors="Rick South"
description='''Whenever a player is teleported via a command, their pets will be teleported alongside them.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.followersteleporttoo]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.followersteleporttoo]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "followersteleporttoo_neoforge.mixins.json"